# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160330_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(verbose_name='Seznam členů'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Název týmu'),
        ),
        migrations.AlterField(
            model_name='team',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
