# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160331_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('info', 'Info (modrá)'), ('warning', 'Warning (žlutá)'), ('danger', 'Danger (červená)'), ('success', 'Success (zelená)')], default='info', max_length=32),
            preserve_default=False,
        ),
    ]
