# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:19
from __future__ import unicode_literals

from django.db import migrations
import timedelta.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='length',
            field=timedelta.fields.TimedeltaField(default=0),
            preserve_default=False,
        ),
    ]
