# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_licence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_strategic',
            field=models.BooleanField(default=False),
        ),
    ]
