# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160401_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='reservation_cnt',
            new_name='reserved',
        ),
    ]
