# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160402_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='reserved',
        ),
    ]
