# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_balance_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
    ]
