# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160402_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': (('play', 'Can play the game as a team'), ('control', 'Can control the game through control panel'))},
        ),
    ]
