# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160409_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='expected',
            field=models.IntegerField(default=0),
        ),
    ]
