# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_balance_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='expected_now',
            field=models.IntegerField(default=0),
        ),
    ]
