# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_balance_expected_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='blocked_now',
            field=models.IntegerField(default=0),
        ),
    ]
