# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_balance_blocked_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_licence',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='licence',
        ),
        migrations.AddField(
            model_name='entity',
            name='licences',
            field=models.ManyToManyField(related_name='licenced_entities', to='core.Entity'),
        ),
    ]
