# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160411_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='licences',
        ),
        migrations.AddField(
            model_name='entity',
            name='is_licence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
    ]
