# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timedelta.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', timedelta.fields.TimedeltaField()),
                ('end', timedelta.fields.TimedeltaField()),
                ('description', models.TextField(max_length=256)),
                ('minimum', models.PositiveIntegerField()),
                ('bid_step', models.PositiveIntegerField()),
                ('transaction_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('visible', models.BooleanField()),
                ('will_sell', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlackAuction',
            fields=[
                ('auction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.Auction')),
                ('seller_name', models.CharField(max_length=128)),
                ('status_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Black market offers',
            },
            bases=('auctions.auction',),
        ),
        migrations.CreateModel(
            name='WhiteAuction',
            fields=[
                ('auction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.Auction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
            bases=('auctions.auction',),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='auctioneditem',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='auctioneditem',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
        migrations.AddField(
            model_name='auction',
            name='wants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('auction', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='auctioneditem',
            unique_together=set([('auction', 'entity')]),
        ),
    ]
