# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
