# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160402_0118'),
        ('auctions', '0002_auto_20160330_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='transaction_made',
            new_name='commited',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='wants',
            new_name='var_entity',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='bid_step',
            new_name='var_step',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='minimum',
        ),
        migrations.AddField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='auction',
            name='var_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whiteauction',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
