# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import timedelta.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20160402_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='placed',
            field=timedelta.fields.TimedeltaField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctioneditem',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
