# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 22:21
from __future__ import unicode_literals

from django.db import migrations
import timedelta.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20160415_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end',
            field=timedelta.fields.TimedeltaField(blank=True, null=True),
        ),
    ]
