# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20160416_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='var_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
    ]
