# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20160418_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackauction',
            name='status_text',
        ),
        migrations.AddField(
            model_name='auction',
            name='status_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
