# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Consumes'), (1, 'Needs'), (2, 'Creates')]),
        ),
    ]
