# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_auto_20160411_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[ABCDEFGHIJKLMNOPQRSTUVWXYZ]{6}')])),
                ('used', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
        ),
    ]
