# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160416_0911'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='used',
        ),
        migrations.AddField(
            model_name='token',
            name='used_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
