# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 09:49
from __future__ import unicode_literals

from django.db import migrations
import timedelta.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20160416_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='used_time',
            field=timedelta.fields.TimedeltaField(blank=True, default=None, null=True),
        ),
    ]
