# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_token_used_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([QWRTPSDFGHJKLZXCVBNM][AEIOUY]){3}[QWRTPSDFGHJKLZXCVBNM]{0}')]),
        ),
    ]
